include("${CMAKE_CURRENT_LIST_DIR}/EnvConfig.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ThirdParty.cmake")

set(SCONE_INNER_BUILD_DIR "${CMAKE_BINARY_DIR}/scone" CACHE PATH "Build directory for the SCONE project.")

set(SCONE_INNER_PREFIX_PATH
	"${OSG_INSTALL_PREFIX}"
	"${SIMBODY_INSTALL_PREFIX}"
	"${OPENSIM_INSTALL_PREFIX}"
)
string(REPLACE ";" "\\;" SCONE_INNER_PREFIX_PATH_JOINED "${SCONE_INNER_PREFIX_PATH}")

ExternalProject_Add(scone_project
	SOURCE_DIR "${CMAKE_SOURCE_DIR}"
	BINARY_DIR "${SCONE_INNER_BUILD_DIR}"
	DEPENDS opensim_ep
	CMAKE_ARGS
		-DSCONE_SUPERBUILD=OFF
		-DCMAKE_BUILD_TYPE=${SCONE_BUILD_TYPE}
		-DCMAKE_INSTALL_PREFIX=${SCONE_INSTALL_PREFIX}
		-DCMAKE_EXPORT_COMPILE_COMMANDS=ON
		-DCMAKE_PREFIX_PATH=${SCONE_INNER_PREFIX_PATH_JOINED}
		-DSCONE_THIRDPARTY_ROOT=${SCONE_THIRDPARTY_ROOT}
		-DOSG_INSTALL_PREFIX=${OSG_INSTALL_PREFIX}
		-DSIMBODY_INSTALL_PREFIX=${SIMBODY_INSTALL_PREFIX}
		-DOPENSIM_INSTALL_PREFIX=${OPENSIM_INSTALL_PREFIX}
		-DOSG_DIR=${OSG_INSTALL_PREFIX}
		-DOPENSIM_INSTALL_DIR=${OPENSIM_INSTALL_PREFIX}
		-DOPENSIM_INCLUDE_DIR=${OPENSIM_INSTALL_PREFIX}/sdk/include
	BUILD_COMMAND ${CMAKE_COMMAND} --build . ${SCONE_BUILD_PARALLEL_FLAG}
	INSTALL_COMMAND ${CMAKE_COMMAND} --build . --target install ${SCONE_BUILD_PARALLEL_FLAG}
)

ExternalProject_Add_Step(scone_project export_compile_commands
	COMMAND ${CMAKE_COMMAND} -E copy_if_different
		"${SCONE_INNER_BUILD_DIR}/compile_commands.json"
		"${CMAKE_BINARY_DIR}/compile_commands.json"
	DEPENDEES configure
	ALWAYS 1
)
