include(ExternalProject)
include(ProcessorCount)

ProcessorCount(SCONE_BUILD_JOBS)
if(NOT SCONE_BUILD_JOBS OR SCONE_BUILD_JOBS EQUAL 0)
	set(SCONE_BUILD_JOBS 1)
endif()
set(SCONE_BUILD_JOBS "${SCONE_BUILD_JOBS}" CACHE STRING "Parallel build jobs for dependency builds.")

if(SCONE_BUILD_TYPE STREQUAL "Debug")
	set(SCONE_OPENSIM_PARALLEL_JOBS 1 CACHE STRING "Parallel build jobs for OpenSim (Debug defaults to 1 to avoid link-order issues)." FORCE)
	set(SCONE_OPENSIM_DEBUG_POSTFIX "" CACHE STRING "Debug postfix for OpenSim libraries." FORCE)
else()
	set(SCONE_OPENSIM_PARALLEL_JOBS "${SCONE_BUILD_JOBS}" CACHE STRING "Parallel build jobs for OpenSim.")
	set(SCONE_OPENSIM_DEBUG_POSTFIX "" CACHE STRING "Debug postfix for OpenSim libraries.")
endif()

if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.12")
	set(SCONE_BUILD_PARALLEL_FLAG "--parallel" "${SCONE_BUILD_JOBS}")
	set(SCONE_OPENSIM_PARALLEL_FLAG "--parallel" "${SCONE_OPENSIM_PARALLEL_JOBS}")
else()
	set(SCONE_BUILD_PARALLEL_FLAG "--" "-j${SCONE_BUILD_JOBS}")
	set(SCONE_OPENSIM_PARALLEL_FLAG "--" "-j${SCONE_OPENSIM_PARALLEL_JOBS}")
endif()

set(OSG_SOURCE_DIR "${CMAKE_SOURCE_DIR}/submodules/OpenSceneGraph")
set(SIMBODY_SOURCE_DIR "${CMAKE_SOURCE_DIR}/submodules/simbody")
set(OPENSIM_SOURCE_DIR "${CMAKE_SOURCE_DIR}/submodules/opensim3-scone")

foreach(dep_path IN LISTS OSG_SOURCE_DIR SIMBODY_SOURCE_DIR OPENSIM_SOURCE_DIR)
	if(NOT EXISTS "${dep_path}/CMakeLists.txt")
		message(FATAL_ERROR "Missing submodule at ${dep_path}. Run: git submodule update --init --recursive")
	endif()
endforeach()

ExternalProject_Add(osg_ep
	SOURCE_DIR "${OSG_SOURCE_DIR}"
	BINARY_DIR "${SCONE_THIRDPARTY_BUILD_ROOT}/osg"
	INSTALL_DIR "${OSG_INSTALL_PREFIX}"
	CMAKE_ARGS
		-DCMAKE_BUILD_TYPE=${SCONE_BUILD_TYPE}
		-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
		-DCMAKE_INSTALL_RPATH=$ORIGIN
		-DCMAKE_POSITION_INDEPENDENT_CODE=ON
		-DOSG_USE_QT=ON
		-DDESIRED_QT_VERSION=5
	BUILD_COMMAND ${CMAKE_COMMAND} --build . ${SCONE_OPENSIM_PARALLEL_FLAG}
	INSTALL_COMMAND ${CMAKE_COMMAND} --build . --target install ${SCONE_OPENSIM_PARALLEL_FLAG}
)

ExternalProject_Add(simbody_ep
	SOURCE_DIR "${SIMBODY_SOURCE_DIR}"
	BINARY_DIR "${SCONE_THIRDPARTY_BUILD_ROOT}/simbody"
	INSTALL_DIR "${SIMBODY_INSTALL_PREFIX}"
	DEPENDS osg_ep
	CMAKE_ARGS
		-DCMAKE_BUILD_TYPE=${SCONE_BUILD_TYPE}
		-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
		-DCMAKE_INSTALL_RPATH=$ORIGIN
		-DCMAKE_POSITION_INDEPENDENT_CODE=ON
		-DBUILD_EXAMPLES=OFF
		-DBUILD_TESTING=OFF
	BUILD_COMMAND ${CMAKE_COMMAND} --build . ${SCONE_BUILD_PARALLEL_FLAG}
	INSTALL_COMMAND ${CMAKE_COMMAND} --build . --target install ${SCONE_BUILD_PARALLEL_FLAG}
)

ExternalProject_Add(opensim_ep
	SOURCE_DIR "${OPENSIM_SOURCE_DIR}"
	BINARY_DIR "${SCONE_THIRDPARTY_BUILD_ROOT}/opensim3"
	INSTALL_DIR "${OPENSIM_INSTALL_PREFIX}"
	DEPENDS simbody_ep
	CMAKE_ARGS
		-DCMAKE_BUILD_TYPE=${SCONE_BUILD_TYPE}
		-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
		-DCMAKE_INSTALL_RPATH=$ORIGIN
		-DCMAKE_POSITION_INDEPENDENT_CODE=ON
		-DCMAKE_DEBUG_POSTFIX=${SCONE_OPENSIM_DEBUG_POSTFIX}
		-DSIMBODY_HOME=${SIMBODY_INSTALL_PREFIX}
		-DBUILD_TESTING=OFF
		-DBUILD_API_EXAMPLES=OFF
		-DBUILD_API_ONLY=OFF
	BUILD_COMMAND ${CMAKE_COMMAND} --build . ${SCONE_BUILD_PARALLEL_FLAG}
	INSTALL_COMMAND ${CMAKE_COMMAND} --build . --target install ${SCONE_BUILD_PARALLEL_FLAG}
)
